// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqkrejkaFCzThpLP1ZDui2h-ZRrdA6db0',
    appId: '1:401881420442:web:fa550042b4602d11d90523',
    messagingSenderId: '401881420442',
    projectId: 'elbigay-database',
    authDomain: 'elbigay-database.firebaseapp.com',
    storageBucket: 'elbigay-database.appspot.com',
    measurementId: 'G-9MX2WL5B8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSaYnm1Kbs3BRraZUnmBtsS57mnjR_MkY',
    appId: '1:401881420442:android:278e1112d22cdf9ad90523',
    messagingSenderId: '401881420442',
    projectId: 'elbigay-database',
    storageBucket: 'elbigay-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNMm5sXsjVt1bYUl3ALbCnxc_y6tMEwbg',
    appId: '1:401881420442:ios:de4c0eace522de8cd90523',
    messagingSenderId: '401881420442',
    projectId: 'elbigay-database',
    storageBucket: 'elbigay-database.appspot.com',
    iosBundleId: 'com.example.elbigay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNMm5sXsjVt1bYUl3ALbCnxc_y6tMEwbg',
    appId: '1:401881420442:ios:de4c0eace522de8cd90523',
    messagingSenderId: '401881420442',
    projectId: 'elbigay-database',
    storageBucket: 'elbigay-database.appspot.com',
    iosBundleId: 'com.example.elbigay',
  );
}
